from . import help
from . import start
from . import contact
from . import location
from . import show_id
from . import handler_document
from . import register
from . import subscribe
from . import echo
